spring.application.name=idrive-api

# Dados de conexão (Ajuste para o seu usuário/senha do Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/idrive_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true