spring.application.name=idrive-api

spring.datasource.url=jdbc:postgresql://localhost:5432/idrive_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=senha_do_token